### ISSUE TITLE
Evaluation Metrics

### ISSUE THREAD

**Issue by fanghaook** [950216/EDRNet#1]
作者，您好！我对您论文中的评价指标比较感兴趣，可否上传一下论文中测试那5个指标的代码，万分感谢！

**Comment by SongGuorong** [comment]
@fanghaook 您好，本论文所使用的评价指标均源于网上开源的代码，其中MAE/WF/OR由_[Salient Object Detection Via Structured Matrix Decomposition](https://sites.google.com/site/salientobjectdetection/evaluation)_的论文作者提供，SM指标的代码也已由_[Structure-Measure: a new way to evaluate foreground maps](https://github.com/DengPingFan/S-measure)_的论文作者提供，若您使用的话请引用相关论文，指标打包代码：[评价指标.zip](https://github.com/950216/EDRNet/files/5287685/default.zip)
