### ISSUE TITLE
Image Size

### ISSUE THREAD

**Issue by 18718277909** [950216/EDRNet#2]
Hello,
     Thanks for your job.
     Can you please tell me is there a limit of the size of my images in my training dataset and testing dataset? And is the code has the image resize?

**Comment by 18718277909** [comment]
你好，我想请问这个训练网络和测试网络，对图片尺寸有要求吗？要统一resize吗？还是你的代码里面已经有resize的代码了？

**Comment by SongGuorong** [comment]
@18718277909 您好，在论文的实验部分我们已经说明了，原图会首先resize到256x256，之后会随机裁剪成224x224，所以对原始图片的大小是没有限制的，不过最好原始图片是方的，这样可以避免一些偏差，另外，不需要你重新resize，已经包含在代码里，只需要更换你所需要的数据集就OK啦

**Comment by 18718277909** [comment]
好的 谢谢
