### ISSUE TITLE
测试结果

### ISSUE THREAD

**Issue by wanbin19921212** [950216/EDRNet#6]
你好我想问一下 表2 的三列  上面的噪声比例 是指训练集的还是测试集的  可否将不同噪声的数据集发一下谢谢！！！

**Comment by SongGuorong** [comment]
您好，噪声比例指的是整个测试数据集，训练集使用了部分，另外，我已经更新了`README.md`文档，在**Supplement**部分，你可以下载到含噪声数据集以及相应的实验结果
